spring.application.name=follow-service

server.port=8091

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

clients.profile-service.url=http://localhost:8081

# Logging
logging.level.org.springframework.data.mongodb=INFO
logging.level.com.example.followservice=DEBUG
clients.notifications-service.url=${NOTIFICATIONS_SERVICE_URL:http://localhost:8085}
