services:
  # 1. The Database
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # 2. Service A: Verification
  verification-service:
    build: ./verification-service  # Path to the folder containing Dockerfile
    container_name: verification_service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker # Activates application-docker.properties
    depends_on:
      - mongodb

  # 3. Service B: Listings
  listing-service:
    build: ./listing-service      # Path to the folder containing Dockerfile
    container_name: listing_service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker # Activates application-docker.properties
    depends_on:
      - mongodb

  # 4. Service C: Order & Reservation
  order-reservation-service:
    build: ./order_reservation-service
    container_name: order_reservation_service
    ports:
      - "8085:8085"
    depends_on:
      - mongodb
    environment:
      - SPRING_MONGODB_URI=mongodb://mongodb:27017/order_reservationdb
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/order_reservationdb


volumes:
  mongo_data: