server.port=8080
spring.application.name=api-gateway

# Route to identity-service
spring.cloud.gateway.routes[0].id=identity
spring.cloud.gateway.routes[0].uri=http://localhost:8082
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**,/internal/**

# Route to profile-service
spring.cloud.gateway.routes[1].id=profiles
spring.cloud.gateway.routes[1].uri=http://localhost:8083
spring.cloud.gateway.routes[1].predicates[0]=Path=/profiles/**