spring.application.name=ListingService

server.port=8084

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=listingdb

# Logging
logging.level.org.springframework.data.mongodb=INFO
logging.level.ca.gbc.comp3095.verificationservice=DEBUG



# Cloudinary Configuration
cloudinary.cloud-name=dctoh7nlf
cloudinary.api-key=145224784627288
cloudinary.api-secret=BjDhSwLFTbccNZn9JOAKQzPETIo
