spring.application.name=ListingService
server.port=8084

# Database Connection
spring.data.mongodb.host=mongodb
spring.data.mongodb.port=27017
spring.data.mongodb.uri=${MONGODB_URI_LISTING}
application.config.profile-url=${PROFILE_SERVICE_BASE_URL:http://profile-service:8081}
application.config.payment-url=${PAYMENT_SERVICE_BASE_URL:http://stripe-payment-service:8090}

# Logging
logging.level.org.springframework.data.mongodb=INFO
# FIX 2: Change package to listingservice
logging.level.ca.gbc.comp3095.listingservice=DEBUG



# Cloudinary Configuration
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

application.config.notifications-url=${NOTIFICATIONS_SERVICE_BASE_URL:http://localhost:8085}
application.config.follow-url=${FOLLOW_SERVICE_BASE_URL:http://localhost:8091}
