spring.application.name=ListingService
server.port=8084

# Database Connection
spring.data.mongodb.host=mongodb
spring.data.mongodb.port=27017
spring.data.mongodb.database=listingdb
spring.data.mongodb.username=root
spring.data.mongodb.password=rootpass
spring.data.mongodb.authentication-database=admin

application.config.profile-url=http://profile-service:8081

spring.cloud.compatibility-verifier.enabled=false

# Logging
logging.level.org.springframework.data.mongodb=INFO
# FIX 2: Change package to listingservice
logging.level.ca.gbc.comp3095.listingservice=DEBUG