spring.application.name=stripe_payment-service
stripe.secret-key=${STRIPE_SECRET_KEY}
stripe.publishable-key=${STRIPE_PUBLISHABLE_KEY}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET}

stripe.return-url=${STRIPE_RETURN_URL}
stripe.refresh-url=${STRIPE_REFRESH_URL}
clients.profileBaseUrl = http://profile-service:8081
clients.orderBaseUrl=${ORDER_SERVICE_BASE_URL:http://localhost:8085}