spring.application.name=community-service
server.port=8088
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
services.identity.base-url=http://identity-service:8082
services.notifications.base-url=http://notifications-service:8085
internal.sharedSecret=${INTERNAL_SHARED_SECRET:dev-internal-secret}
spring.cloud.compatibility-verifier.enabled=false
