server.port=8088
spring.application.name=community-service
spring.data.mongodb.uri=mongodb://root:rootpass@localhost:27017/community_db?authSource=admin
services.identity.base-url=http://localhost:8082
services.notifications.base-url=http://localhost:8085
internal.sharedSecret=${INTERNAL_SHARED_SECRET:dev-internal-secret}
