FROM eclipse-temurin:21-jre

ARG SERVICE_DIR
ARG APP_PORT

WORKDIR /app
COPY ${SERVICE_DIR}/build/libs/*.jar app.jar

EXPOSE ${APP_PORT}

ENV JAVA_OPTS="-Xms64m -Xmx160m -XX:+UseSerialGC -XX:MaxMetaspaceSize=128m -XX:ReservedCodeCacheSize=48m"

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]
