server.port=8081
spring.application.name=profile-service

# CHANGE 1: Host is 'mongodb', not 'localhost'
spring.data.mongodb.uri=mongodb://root:rootpass@mongodb:27017/profiles_org_db?authSource=admin
spring.data.mongodb.auto-index-creation=true

# CHANGE 2: Identity service is at its container name (if you add it later)
clients.identityBaseUrl=http://identity-service:8082
internal.sharedSecret=${INTERNAL_SHARED_SECRET:dev-internal-secret}
security.jwt.secret=${JWT_SECRET:jiyyjgqevnufmhclohfveoldjuyuxcys}