server.port=8081
spring.application.name=profile-service

# Mongo
spring.data.mongodb.uri=${MONGODB_URI_PROFILE}
spring.data.mongodb.auto-index-creation=true

# JWT secret used to validate tokens issued by identity-service
security.jwt.secret=${JWT_SECRET:jiyyjgqevnufmhclohfveoldjuyuxcys}

# Identity service base URL (for role upgrade call)
clients.identityBaseUrl=${IDENTITY_SERVICE_URL:http://localhost:8082}

# Same internal secret for calling identity-service internal endpoint
internal.sharedSecret=${INTERNAL_SHARED_SECRET:dev-internal-secret}

