server.port=8081
spring.application.name=profile-service

spring.data.mongodb.uri=${MONGODB_URI_PROFILE}
spring.data.mongodb.auto-index-creation=true

clients.identityBaseUrl=http://identity-service:8082
clients.verificationBaseUrl=http://verification-service:8083
clients.adminBaseUrl=http://admin-service:8087
internal.sharedSecret=${INTERNAL_SHARED_SECRET:dev-internal-secret}
security.jwt.secret=${JWT_SECRET:jiyyjgqevnufmhclohfveoldjuyuxcys}
clients.notificationsBaseUrl=http://notifications-service:8085
