server.port=8081
spring.application.name=profile-service

spring.data.mongodb.uri=${MONGODB_URI_PROFILE}
spring.data.mongodb.auto-index-creation=true

clients.identityBaseUrl=http://identity-service:8082
internal.sharedSecret=${INTERNAL_SHARED_SECRET:dev-internal-secret}
security.jwt.secret=${JWT_SECRET:jiyyjgqevnufmhclohfveoldjuyuxcys}