server.port=8085
spring.application.name=notifications-service

spring.data.mongodb.uri=mongodb://root:rootpass@localhost:27017/notifications_db?authSource=admin

services.identity.base-url=http://localhost:8082
internal.sharedSecret=${INTERNAL_SHARED_SECRET:dev-internal-secret}
