spring.application.name=notifications-service
server.port=8085
services.identity.base-url=http://identity-service:8082
internal.sharedSecret=${INTERNAL_SHARED_SECRET:dev-internal-secret}

spring.cloud.compatibility-verifier.enabled=false
