spring.application.name=VerificationService
server.port=8083

spring.data.mongodb.host=mongodb
spring.data.mongodb.port=27017
spring.data.mongodb.database=verificationdb
spring.data.mongodb.username=myuser
spring.data.mongodb.password=rootpass
spring.data.mongodb.authentication-database=admin


application.config.profile-url=http://profile-service:8081

spring.cloud.compatibility-verifier.enabled=false

# Logging
logging.level.org.springframework.data.mongodb=INFO
logging.level.ca.gbc.comp3095.verificationservice=DEBUG

clients.identityBaseUrl=http://identity-service:8082
internal.sharedSecret=${INTERNAL_SHARED_SECRET}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# Cloudinary Configuration
cloudinary.cloud-name=dctoh7nlf
cloudinary.api-key=145224784627288
cloudinary.api-secret=BjDhSwLFTbccNZn9JOAKQzPETIo

