spring.application.name=stripe_payment-service
server.port=8090

stripe.secret-key=${STRIPE_SECRET_KEY}
stripe.publishable-key=${STRIPE_PUBLISHABLE_KEY}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET}

stripe.return-url=${STRIPE_RETURN_URL:http://localhost:9000/api/stripe/onboarding/return}
stripe.refresh-url=${STRIPE_REFRESH_URL:http://localhost:9000/api/stripe/onboarding/refresh}
app.frontend-profile-url=${FRONTEND_PROFILE_URL:http://localhost:5173/profile}
app.public-platform-base-url=${PUBLIC_PLATFORM_BASE_URL:http://localhost:5173}

spring.data.mongodb.uri=${MONGODB_URI_PAYMENT}

clients.profileBaseUrl=${PROFILE_SERVICE_BASE_URL:http://localhost:8081}
clients.orderBaseUrl=${ORDER_SERVICE_BASE_URL:http://localhost:8086}
