spring.application.name=order_reservation-service
server.port=8086

#format: mongodb://host:port/database_name
spring.data.mongodb.uri=${MONGODB_URI_LISTING}

listing.service.base-url=${LISTING_SERVICE_BASE_URL:http://localhost:8084}


logging.level.com.locally=DEBUG