server.port=8085

spring.application.name=order-reservation-service

spring.data.mongodb.uri=mongodb://mongodb:27017/order_reservationdb

spring.jackson.serialization.write-dates-as-timestamps=false

logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE

