spring.application.name=rating-review-service
server.port=8089

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

clients.orderReservationBaseUrl=http://order-reservation-service:8086
internal.sharedSecret=${INTERNAL_SHARED_SECRET}

# Logging
logging.level.org.springframework.data.mongodb=INFO
logging.level.com.example.reviewservice=DEBUG